Update job

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,6 +3,8 @@ on:
   push:
     branches:
       - main
+  schedule:
+    - cron: '0 */4 * * *'
 
 jobs:
   run-script:
@@ -31,6 +33,11 @@ jobs:
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git add .
           git commit -m 'Update auto rules'
-          git push origin HEAD:main
+          if [ $? -eq 0 ]; then
+            echo "Commit successful. Pushing to repository..."
+            git push origin HEAD:main
+          else
+            echo "Commit failed. Aborting push."
+          fi
         # env:
         #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
